import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Union


def detect_calculation_code(filepath: Union[str, Path]) -> tuple:
    """
    Define the DFT code used for the calculation based on file content.
    """
    filepath = Path(filepath)

    try:
        with open(filepath, "rb") as f:
            header = f.read(2048)  # first 2KB for detection
    except Exception as e:
        return "unknown", f"Error: {e}"

    # xml fleur
    if header.startswith(b"<?xml"):
        try:
            tree = ET.parse(filepath)
            root = tree.getroot()

            # FLEUR XML tags
            if root.tag in ["fleurOutput", "fleurInput"]:
                return "fleur", "FLEUR XML file"
            elif root.find(".//iteration") is not None:
                return "fleur", "FLEUR out.xml"
        except:
            pass
        return "xml", "Generic XML"

    # txt files
    try:
        text = header.decode("utf-8", errors="ignore")

        # FLEUR signatures
        fleur_sigs = [
            "This output is generated by fleur",
            "This is FLEUR version",
            "fleur 37",
            "fleur 36",
            "fleur 35",
            "FERHIS Fermi-Energy",
            "FERHIS: Fermi-Energy",
            "total energy=",
            "l-like charge",
            "density convergence",
            "subroutine atom2",
            "atom2 entered",
        ]

        # CRYSTAL signatures
        crystal_sigs = [
            "CRYSTAL17",
            "CRYSTAL14",
            "CRYSTAL23",
            "EEEE    CCCC  RRRR",
            "UNIVERSITY OF TORINO",
            "TOTAL ENERGY(DFT)",
            "SCF ENDED",
            "DIRECT LATTICE VECTORS",
            "PRIMITIVE CELL",
            "SHRINK FACTORS",
        ]

        # count matches
        fleur_score = sum(1 for sig in fleur_sigs if sig in text)
        crystal_score = sum(1 for sig in crystal_sigs if sig in text)

        if fleur_score > 0 and fleur_score >= crystal_score:
            return "fleur", f"FLEUR (matches: {fleur_score})"
        elif crystal_score > 0:
            return "crystal", f"CRYSTAL (matches: {crystal_score})"

    except:
        pass

    return "unknown", "Unknown code"


if __name__ == "__main__":
    # path = Path("/root/projects/ab_initio_calculations/fleur_input_copy_2/sym.xml")
    path = Path(
        "/root/projects/ab_initio_calculations/output_fleur/20250623_171647_827/out"
    )
    # path = Path("/root/projects/ab_initio_calculations/output_crystal/20250628_115541_8/fort.34")
    code, reason = detect_calculation_code(path)
    print(f"Detected code: {code} ({reason})")
